@@include('files/burger-menu.js', {})
@@include('files/anchor-scroll.js', {})
@@include('files/tabs.js', {})
@@include('files/spollers.js', {})
@@include('libs/swiper.min.js', {})
@@include('files/script.js', {})